name: Patreon Market Bot

on:
  schedule:
    - cron: '15 9 * * 1-5'
  workflow_dispatch: # This line adds a manual "Run" button for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
